### ISSUE TITLE
Is com-liferay-apio-architect dead as it it is not part of master anymore?

### ISSUE THREAD

**Issue by sammso** [liferay/com-liferay-apio-architect#350]
Is com-liferay-apio-architect dead as it it is not part of master anymore?

**Comment by sammso** [comment]
My bad, it seems that there has been some kind of structure change at only. Nevermind

**Comment by JorgeFerrer** [comment]
Hey Sampsa, I would not recommend using Apio Architect any more. We have decided to use a different approach which starts from an OpenAPI definition and generate code from it (similar to how Service Builder works, although at the REST layer and obviously decoupled from the internals). We are rebuilding a good number of the features of Apio Architect into this new approach, but it does not have good support for Hypermedia or embedded yet, among other reasons because OpenAPI does not support it natively yet.

**Comment by sammso** [comment]
Thank you, @JorgeFerrer
